### ISSUE TITLE
"soft-require" is required as meta data 3.2.1

### ISSUE THREAD

**Issue by Supermillhouse** [brunoais/phpbbextf_read_other#10]
I get this error with your latest commit.
Required meta field soft-require has not been set.
![untitled](https://user-images.githubusercontent.com/5963597/30693999-fb556340-9ec9-11e7-9f9c-5ef3ad280057.png)

**Comment by Galixte** [comment]
Hi @brunoais,

could you take a look, please?

**Comment by brunoais** [comment]
Sorry about the delay. I got sidetracked.
