### ISSUE TITLE
empty forums

### ISSUE THREAD

**Issue by Supermillhouse** [brunoais/phpbbextf_read_other#14]
Empty forums should display as "No Posts" or "Classified Information" instead of "By-"
![image](https://user-images.githubusercontent.com/5963597/41474494-0bce3a28-70b4-11e8-85a4-71f6b288ab91.png)

**Comment by brunoais** [comment]
I saw this one and forgot to label it.... I also forgot if I solved it.
May you please confirm... Maybe I will at some point. Worst case, after this extension is accepted into the database

**Comment by brunoais** [comment]
No answer in too long. Closing
