### ISSUE TITLE
Sugestion to solve the search problem (as said in the forum)

### ISSUE THREAD

**Issue by alex9099** [brunoais/phpbbextf_read_other#2]
Hi, dont know if this is the best place to give a sugestion about solving that problem, but here it goes :D 

Have you tryed to "sniff" the search results and only show the ones that the owner is the same as the user that is logged in?

That might solve the problem :) 

EDIT: does disabling search function solves the problem?

**Comment by brunoais** [comment]
I did.
But that either messes up with the cached results (this event is not called):
E.g1. https://github.com/brunoais/phpbbextf_read_other/blob/master/event/main_listener.php#L774
Or messes up with the number of returned results:
E.g2. https://github.com/brunoais/phpbbextf_read_other/blob/master/event/main_listener.php#L723

Currently, no actual information about which topics were hidden is being leaked but the sheer fact that topics are not being listed is enough to infer that some sort of filtering is happening there.

> EDIT: does disabling search function solves the problem?

That is a workaround, not a solution. I don't like workarounds unless strictly necessary. That's a nasty one too!
Regardless, if you disable the search, this extension is supposed to be working perfectly well. I couldn't find any issues in my tests.

**Comment by alex9099** [comment]
Yea, i dont like workarrounds also, but in my case i would not need search so it is ok :) i'll test it, and then i'll give feedback

**Comment by brunoais** [comment]
Thanks.

**Comment by alex9099** [comment]
It is not working, maybe i did something wrong :/ 

I'm using version 3.1.10 and i extracted the folder inside the zip to the ext folder, i get a 500 error :(

**Comment by brunoais** [comment]
Did you follow the installation instructions?
https://www.phpbb.com/community/viewtopic.php?f=456&t=2283001

**Comment by alex9099** [comment]
Yes

EDIT: ... nevermind... i forgot to change permissions of the folder with extensions, so php behind the 500 error may was giving a access denied error :D 

EDIT.. again: It does not give the 500 error, but it does not show on the extension page

LAST EDIT... i think: Finally it appeared, i tought it was to extract the folder to forum/ext/brunoais/readOthersTopics/phpbbextf_read_other-master but no... it was to extract to forum/ext/brunoais/readOthersTopics/ :+1:

**Comment by brunoais** [comment]
*tsk* They changed how the archives are archived. Seems like they now put everything inside a directory inside the archive. I'll change the instructions to reflect that. Thanks for warning me.

**Comment by brunoais** [comment]
I'll close this as the subject has changed and there doesn't seem to be anything pending here.
