### ISSUE TITLE
Error reported on main page when enabled #BUG #ASAP

### ISSUE THREAD

**Issue by anoduck** [brunoais/phpbbextf_read_other#20]
Dearly need this extension working, as for it serves a critical role in my current deployment of phpbb. 

PHPbb Version: 3.3.1 (Current)
PHP version: 7.3.21
PHP Mysql driver: mysqli
Database: 10.4.13-MariaDB
Installation Method: Git Clone from repo

When plugin is enabled, error message is reported on main index page of site.  
```
[phpBB Debug] PHP Warning: in file [ROOT]/ext/brunoais/readOthersTopics/event/main_listener.php on line 262: Invalid argument supplied for foreach() 
[phpBB Debug] PHP Warning: in file [ROOT]/ext/brunoais/readOthersTopics/event/main_listener.php on line 270: sizeof(): Parameter must be an array or an object that implements Countable
```

Appears to be a syntax error as a result of using the current version of PHPbb or more current version of php.

**Comment by brunoais** [comment]
I tried to reproduce what you tell but I don't get those warnings.
Your extension version appears to be 3 years old `1.1.0`, and not the `1.2.0`.
I've made some changes since then. Test again with the latest version pls.

**Comment by anoduck** [comment]
Issued a git commit && git pull and my current version is now `1.3.0`. I am not sure where to get `1.2.0`, it is not in the PHPbb customization database (which is `1.1.0`), the newest release here is also `1.1.0`, and it was not on the forum thread linked in the README.md.

I am still getting the error and it is a shame the error is not reproducible. Any tips on how to debug the extension to discover why the error is occurring?

**Comment by brunoais** [comment]
I created `1.3.0` in the meantime using one information I got elsewhere.

As for the reproduction:
Try making a database and code clone of your current forum instance and only install my extension. Check if the problem maintains. If not, keep adding extensions one by one.
This will help finding which extensions are incompatible with mine and helps me know what to do about it.

If you get the error, try getting a "clean" version of the database without users personal data and send it to me.
If you want, I can get a dump of my current testbench forum and you can try playing with it to get the problem to appear.

**Comment by anoduck** [comment]
Ya know, I never considered another extension could be interfering with readOthersTopics. 

Going to create a test instance using docker and phpbb with bitnami. This is not at all like my current instance but will provide a way for me to test out if another extension is interfering with it. and causing it to go bananas. 

If this fails, I will then attempt to disable all the other extensions and then re-enable them one by one to see if that creates the same problem. 

Will report back findings when available.

**Comment by brunoais** [comment]
OK. Thank you for the feedback.

**Comment by anoduck** [comment]
Well, here is the scoop... I was not able to get the error to reproduce on my test forum either. I am going to start disabling unnecessary extensions and see if that gets me anywhere. This is rather disappointing, that a solution still remains out of grasp, and rather irritating because it has now become a hell of a lot more complicated to find where the extension is hanging and find a solution. Oh, fiddlesticks!

**Comment by anoduck** [comment]
Disabled extensions down to the absolute bare minimum, while still allowing it to be unnoticeable, and got nothing. Next I am going to restore a backup of the board to the test server and see if that effects anything. 

#### These are my enabled extensions:

```
Enabled
-------

 * alex75/background
 * alex75/redtitlenewpost
 * alfredoramos/markdown
 * dmzx/deleteinactiveusers
 * dmzx/filedownload
 * dmzx/forumnameintopic
 * dmzx/modxcommands
 * dmzx/newtopic
 * dmzx/prevnext
 * dmzx/whovisitedthistopic
 * galandas/news
 * ganstaz/esffs
 * ger/modbreak
 * gfksx/thanksforposts
 * hifikabin/headerbanner
 * hifikabin/quotethumbnails
 * kasimi/loginrequired
 * kasimi/postnumbers
 * kasimi/sorttopics
 * kinerity/knowledgebase
 * kinerity/postcountrequirements
 * lmdi/multilinks
 * martin/externallinkinnewwindow
 * paul999/mention
 * paybas/recenttopics
 * phpbb/boardannouncements
 * phpbb/boardrules
 * phpbbes/scrolltoupdown
 * phpbbmodders/banhammer
 * rmcgirr83/hidebots
 * rmcgirr83/topicrestriction
 * rmcgirr83/userpostsinatopic
 * rubencm/customregistrationagreement
 * senky/removesubjectfromreplies
 * threedi/topicshierarchy
 * vinny/rememberme
 * vse/abbc3
 * vse/passwordstrength
 * vse/similartopics
```
 I have tried disabling, check the plugin, and then re-enable them to see if this changes anything. So far I have not noticed any particular reason for the error to occur.

**Comment by brunoais** [comment]
Oh boy... We're in for a fun ride :D

**Comment by anoduck** [comment]
> Oh boy... We're in for a fun ride :D

Now you understand my dilemma. It is like trying to find a needle in a haystack. 

But, it is reasonable to assume the error is derived from the residue of old code left in the database. Now just working on isolating what table it is in the database that contains the old code, exporting that to the test server, and then attempting to recreate the error.

**Comment by brunoais** [comment]
Good luck m8!

**Comment by anoduck** [comment]
Appears to be OpenBSD specific.

**Comment by anoduck** [comment]
Only occurs on the index page. Regardless, I am done, quit, and giving up.

**Comment by brunoais** [comment]
Sad I can't help...
