### ISSUE TITLE
[Suggestion] Alternative for enabling sticky threads when blocking.

### ISSUE THREAD

**Issue by itcotta** [brunoais/phpbbextf_read_other#3]
Hey, I find this extension really useful and there is only one thing that is preventing my community from using it.
Is there any chance if it's not too complicated to when preventing a certain user group from reading threads started from other people to still let them see the sticky/announcement threads from that forum section?
That would be extremly useful.
Thanks and happy holidays!

**Comment by brunoais** [comment]
Hey.
Use local forum announcements instead of sticky threads. That's how it is designed.
If that's no good for you reopen this and, let me know.

**Comment by itcotta** [comment]
Hey, I tried to set it as announcement, and people are able now to see the thread as an announcement but they cannot access them, if they try to access it they get a "You are not authorised to read this topic." information message.
