### ISSUE TITLE
Guests can't access announcements when "Can read topics started by others" is disabled.

### ISSUE THREAD

**Issue by itcotta** [brunoais/phpbbextf_read_other#5]
This is about closed issue #3 
I tried to set it as announcement, and people are able now to see the threads as an announcement but they cannot access them, if they try to access it they get a "You are not authorised to read this topic." information message.

This is what the permissions look like:
Actions:
http://i.imgur.com/D2jHVVY.png

**Comment by brunoais** [comment]
I'll look at it when I get home

**Comment by itcotta** [comment]
ok thanks 👍

**Comment by brunoais** [comment]
I finally was able to get what probably was wrong with this.
Try downloading the from the master branch and test it:
https://github.com/brunoais/phpbbextf_read_other/tree/master
