### ISSUE TITLE
Topic title in Calendar 

### ISSUE THREAD

**Issue by AlSarsawi** [brunoais/phpbbextf_read_other#7]
Hello

first of all i would like to thank you for your great work

I am using calendar ext. in my website
http://calendar.zoo-am-ring.de/index.php
https://www.phpbb.de/community/viewtopic.php?f=149&t=233145

its allow me to add events by writing topics and link them with the calendar
the topic title will appear in the calendar to everyone
except those who don't have the permission to see and read the forum category which the topic inside it

by using your ext.
users who don't have the permission will not see and read topic started by others
but in the calendar they still can see the topic title
can you fix this please

Thank you

**Comment by brunoais** [comment]
I can't fix it myself.
Ask HJW to chat with me to get that to work on my ext.
He must be willing to adjust his extension (or explain to me, in case he uses events) so it works on his extension.

**Comment by AlSarsawi** [comment]
can you please adjust these lines to make your ext. work with the calendar
ext\hjw\calendar\event\main_listener.php, line 577
ext\hjw\calendar\includes\calendar_event.php, line 121

`if (isset($auth_array[$user_id][$row['forum_id']]['f_read']) && $auth_array[$user_id][$row['forum_id']]['f_read'])`

**Comment by brunoais** [comment]
Those lines are not from my extension.

**Comment by AlSarsawi** [comment]
I really don't know which ext. must adjust to make both ext. work together
can you please contact with him to make this happen
I will appreciate that

**Comment by brunoais** [comment]
> Ask HJW to chat with me to get that to work on my ext.

**Comment by AlSarsawi** [comment]
I talked with him and he said these are the two lines which must be adjust to make the calendar work with your extension 
https://www.phpbb.de/community/viewtopic.php?f=149&t=233145&e=1&view=unread#p1368894

please tell me if you need some more specific information's and i will ask him

**Comment by brunoais** [comment]
What he told was how to change his own extension, which I don't have permissions to and I don't intent to meddle with.
In order to get what you want, I need him to change his extension and tell me what API I need to provide to his extension.

**Comment by brunoais** [comment]
It took too long to get any information and almost one year has passed. I'm closing this
