### ISSUE TITLE
Searching is broken

### ISSUE THREAD

**Issue by Valleriani** [brunoais/phpbbextf_read_other#8]
Searching works fine if you have access to read all other topics.

Otherwise if you do not have access, when you search, you get blank results, this occurs on ALL forums though, not just ones you limit with your plugin.

**Comment by brunoais** [comment]
This seems to be an oldish bug which has already been fixed.
Make sure you are using the latest from master branch. If so, please try getting me more information about your BB setup relative to permissions.

**Comment by brunoais** [comment]
6 days without answer. I'm closing this because I can't work without information.

**Comment by YoOoster** [comment]
> 6 days without answer. I'm closing this because I can't work without information.

I'm having the same issues with the search function but instead of occuring it on all forums it just affects a few forums. The ones that can be searched and the ones that can't all have the same permissions.

Using the latest from master branch.

**Comment by brunoais** [comment]
Do you have any idea when does search work and when search doesn't work?
What permissions do the users with the problems have?
Which are the forums permissions?

**Comment by YoOoster** [comment]
This only happens with the registered users group.
Admin and moderator group can search normally. 

For example I have 4 forums:

- Contact Form (Topics of others can't be seen)
- Forum 1 (Shows up in search)
- Forum 2 (Doesn't shows up in search)
- Forum 3 (Shows up in search)

Contact Form registered users permissions:
![chrome_2019-01-08_18-14-59](https://user-images.githubusercontent.com/8483369/50847232-5a603f00-1371-11e9-9aad-8f60f0ddac24.png)

Forum 1 registered users permissions:
![chrome_2019-01-08_18-18-12](https://user-images.githubusercontent.com/8483369/50847394-c773d480-1371-11e9-8d2e-a7da3d4b8cbb.png)

Forum 2 registered users permissions:
![chrome_2019-01-08_18-19-00](https://user-images.githubusercontent.com/8483369/50847447-e2dedf80-1371-11e9-9ccc-a7fd00d5cd13.png)

Forum 3 registered users permissions:
![chrome_2019-01-08_18-20-00](https://user-images.githubusercontent.com/8483369/50847494-06a22580-1372-11e9-8785-ffab3073495c.png)

Registered user global permissions:
![chrome_2019-01-08_18-21-30](https://user-images.githubusercontent.com/8483369/50847591-46690d00-1372-11e9-9f95-1a9a6132afe1.png)

I've also tried to delete the search index and remake it but that didn't help.

Search settings:
![chrome_2019-01-08_18-26-20](https://user-images.githubusercontent.com/8483369/50847854-f2aaf380-1372-11e9-8b6c-2ad87298b698.png)

**Comment by brunoais** [comment]
Thanks. That helps a lot.
One more important thing:
About the forums, what are the parent-child forum relationship between them?

**Comment by YoOoster** [comment]
> Thanks. That helps a lot.
> One more important thing:
> About the forums, what are the parent-child forum relationship between them?

Forum 1,2 and 3 have the same parent. Contact form a different one.
All of them have this permission on:
![chrome_2019-01-08_18-45-51](https://user-images.githubusercontent.com/8483369/50848886-bcbb3e80-1375-11e9-8039-301b2caf066a.png)

**Comment by brunoais** [comment]
Weird indeed. It really doesn't seem to add up.
I'll try solving this as soon as I can squeeze it in my free time. I expect that either next week or the week after.

**Comment by brunoais** [comment]
So much easier said than done... Ish... Not even on a pandemic situation I find the time.
Does this problem still exist?

**Comment by YoOoster** [comment]
I no longer have the problem.
It got fixed when I reorganized my forum structure.

**Comment by brunoais** [comment]
OK. Got it. Thank you.
