### ISSUE TITLE
People can see the thread name and that there is a new post

### ISSUE THREAD

**Issue by Valleriani** [brunoais/phpbbextf_read_other#9]
If you do not have access to see the other peoples threads, but someone makes a post, you can see their post in the thread listing. The icon for 'new posts' is also visible. 

Showing an example. This person does NOT have access to view it. Biggset issue is that the icon highlights though, OCD wise it makes me go crazy because I the only way to remove that is to mark all as read. 

![thread](https://user-images.githubusercontent.com/503080/27628032-0becf840-5bee-11e7-824d-c49c58e4cb4c.png)

**Comment by Valleriani** [comment]
Apparently it is because it is a subforum. If it is not a subforum is says 'classified information'. will adjust it for now on my end though..

**Comment by brunoais** [comment]
Thanks. Apparently it works differently inside when related to subforums. I'll fix that next time I have time....

**Comment by Galixte** [comment]
Hi @brunoais,

could you fix this, please?

**Comment by brunoais** [comment]
@Valleriani @Galixte Very sorry about the delay. I had to plan 2 months in advance to get time for things like this.

**Comment by Galixte** [comment]
No problem, thank you. ;)
